import type { ConfigType } from "@mandafunk/config/types";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Indents every line of a multi-line string by the given number of spaces.
 */
function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? pad + line : line))
    .join("\n");
}

function headerComment(): string {
  return [
    "// Generated by MandaStudio",
    `// Date: ${new Date().toISOString().slice(0, 10)}`,
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// ConfigVariations.js
// ---------------------------------------------------------------------------

interface ConfigVariationEntry {
  name: string | null;
  config: ConfigType;
}

/**
 * Generate ConfigVariations.js content.
 * Groups all unique assigned configs into an exported array.
 */
export function generateConfigVariationsJs(
  configs: ConfigType[],
  names?: Array<string | null>,
): string {
  const entries: ConfigVariationEntry[] = configs.map((config, i) => ({
    name: names?.[i] ?? null,
    config,
  }));

  const variationBlocks = entries.map((entry, index) => {
    const label = entry.name ? `"${entry.name}"` : `Unnamed`;
    const configJson = JSON.stringify(entry.config, null, 2);
    return `  // Variation ${index}: ${label}\n${indent(configJson, 2)}`;
  });

  return [
    headerComment(),
    "export const ConfigVariations = [",
    variationBlocks.join(",\n"),
    "];",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// tracks.js
// ---------------------------------------------------------------------------

interface TrackEntry {
  url: string;
  year: string;
  author: string[];
  filename: string;
  bleep?: boolean;
  pouet?: boolean;
}

/**
 * Generate tracks.js content with shader assignments.
 * Each track gets a `shader: N` property pointing to its ConfigVariations index.
 *
 * @param tracks         - The array of track metadata.
 * @param shaderIndices  - Map of trackIndex to config variation index.
 */
export function generateTracksJs(
  tracks: TrackEntry[],
  shaderIndices: Map<number, number>,
): string {
  const trackLines = tracks.map((track, trackIndex) => {
    const parts: string[] = [
      `    url: ${JSON.stringify(track.url)}`,
      `    year: ${JSON.stringify(track.year)}`,
      `    author: ${JSON.stringify(track.author)}`,
      `    filename: ${JSON.stringify(track.filename)}`,
    ];

    if (track.bleep === true) parts.push("    bleep: true");
    if (track.pouet === true) parts.push("    pouet: true");

    const shaderIdx = shaderIndices.get(trackIndex);
    if (shaderIdx !== undefined) {
      parts.push(`    shader: ${shaderIdx}`);
    }

    return `  {\n${parts.join(",\n")},\n  }`;
  });

  return [
    headerComment(),
    "const tracks = [",
    trackLines.join(",\n"),
    "];",
    "",
    "export function getTracks() { return tracks; }",
    "export function getTrackByPos(pos) { return tracks[pos]; }",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// TypeScript export
// ---------------------------------------------------------------------------

interface NamedConfig {
  name: string;
  config: ConfigType;
}

/**
 * Generate TypeScript export content.
 * Exports as `Record<string, ConfigType>`.
 */
export function generateTypescriptExport(namedConfigs: NamedConfig[]): string {
  const entries = namedConfigs.map(({ name, config }) => {
    const configJson = JSON.stringify(config, null, 2);
    return `  ${JSON.stringify(name)}: ${indent(configJson, 2).trimStart()}`;
  });

  return [
    headerComment(),
    'import type { ConfigType } from "@mandarine/mandafunk/config/types";',
    "",
    "export const scenes: Record<string, ConfigType> = {",
    entries.join(",\n"),
    "};",
    "",
  ].join("\n");
}
