jobs:

  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set Node.js 18.x
          uses: actions/setup-node@v4
            with:
              node-version: 18.x

        - name: Run install
          uses: borales/actions-yarn@v4
          with:
            cmd: install 

        - name: Run install
          uses: borales/actions-yarn@v4
          with:
            cmd: build 

  copy:
      name: Copy file to electron
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4