const authors = {
  bacter: {
    name: "Yitzchak Shemesh-Sarel",
    country: "Israel",
  },
  cemik: { country: "Sweden" },
  "dna-groove": { name: "Eliran Ben-Ishay", country: "Israel" },
  dualtrax: { name: "Marco Stahl", country: "Germany" },
  drax: { country: "Danemark" },
  edzes: { name: "Andreas Bruvoll Skaarung", country: "Norway" },
  ernestoaeroflot: { name: "Teemu Kiiskilä", country: "Finland" },
  forsaken: {},
  genuiz: { name: "Marek Nowak", country: "Germany" },
  jashiin: { name: "Vladimir Seletsky", country: "Russia" },
  keen: { name: "Alexey Komarchuck", country: "Ukraine" },
  kenet: { name: "Raphaël Quercy", country: "France" },
  keyg: { name: "Konrad Gmurek", country: "Poland" },
  ks: { name: "Fabien Lasserre", country: "France" },
  med: { name: "Cyril Pereira", country: "France" },
  nagz: { name: "David Halmi", country: "Hungary" },
  poulpy: {},
  redribbon: { name: "Guillaume Romero", country: "France" },
  rez: { name: "Christophe Resigné", ountry: "France" },
  skybax: { name: "Jonny Jansson", country: "Finland" },
  tomaes: { country: "Germany" },
  traven: { name: "Romain Gauthier", country: "France" },
  unaware: { name: "Marcin Stachyra", country: "Poland" },
  vhiiula: { name: "Andre Seffrin", country: "Germany" },
  wayfinder: { country: "Germany" },
  willbe: { name: "William Lamy", country: "France" },
  xerxes: { name: "Klaus Lunde", country: "Norway" },
};

export default authors;
