import clean from "./clean";

export default {
  ...clean,
  scene: {
    shader: "Med1",
    background: "./images/w13.jpg",
    shader_speed: 0.75,
    shader_opacity: 0.25,
    shader_zoom: 0.5,
    shader_sin_cos_x: true,
    shader_sin_cos_y: true,
    shader_sin_cos_speed: 0.15,
    shader_sin_cos_space: 200,
    blur: 5,
    brightness: 50,
    bgColor: "#000000",
  },
  timer: {
    opacity: 0.52,
  },
  vumeters: {
    oscilloscop: {
      show: true,
      color: "#FFFF00",
      z: -180,
    },
  },
  composer: {
    bloom: { show: true, strength: 0.43, threshold: 0.3, radius: 1 },
    film: {
      show: true,
      count: 1500,
      sIntensity: 1,
      nIntensity: 0.2,
      grayscale: false,
    },
    hue: { show: false },
    rgb: { show: false },
    static: { show: false },
  },
  texts: {
    title: {
      show: true,
      order: 0,
      text: "Analogik",
      font: "Lobster",
      x: 0,
      y: 130,
      z: -650,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      size: 150,
      color: "#55DDFF",
    },
    subtitle: {
      show: true,
      order: 0,
      text: "Chiptune netlabel",
      font: "Kdam Thmor Pro",
      x: -70,
      y: -19,
      z: -650,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      size: 39,
      color: "#aaa",
    },
  },
};
